name: Windows Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        mode: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - uses: microsoft/setup-msbuild@v1.0.0

    - name: CMake
      run: cmake -G "Visual Studio 16 2019" -A x64 -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.mode }}

    - name: Build
      run: cmake --build build  --config ${{ matrix.mode }} --target res-example

    - name: Run tests
      run: build\${{ matrix.mode }}\res-example.exe
